version: '3.9'
services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim
    container_name: ifbank_oracle_container
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: senha123
      APP_USER: ifbank_database
      APP_USER_PASSWORD: senha123
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./src/main/resources/schema.sql:/container-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    restart: unless-stopped
    networks:
      - ifbank-network
  api-ifbank:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ifbank_spring_container
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      DB_USER: ifbank_database
      DB_PASSWORD: senha123
      UPLOAD_DIR: /app/uploads
      MAIL_USERNAME: s.thomaz@aluno.ifsp.edu.br
      MAIL_PASSWORD: buyz uiai elfq fref
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      oracle-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ifbank-network
volumes:
  oracle_data:
  uploads_data:
networks:
  ifbank-network:
    driver: bridge