-- ====================================================================
-- SCRIPT DE CRIAÇÃO DO BANCO - IFBANK (MODELO SIMPLIFICADO)
-- BANCO: Oracle Database (ifbank_database)
-- SEMANA 1: Tabelas de Enum & Fundação 
-- ====================================================================

-- ====================================================================
-- 1. LIMPEZA PRÉVIA PADRONIZADA EM UPPERCASE
-- ====================================================================
DROP TABLE RecuperacaoSenha CASCADE CONSTRAINTS;
DROP TABLE ParcelasEmprestimos CASCADE CONSTRAINTS;
DROP TABLE Emprestimos CASCADE CONSTRAINTS;
DROP TABLE Movimentacoes CASCADE CONSTRAINTS;
DROP TABLE AplicacoesInvestimentos CASCADE CONSTRAINTS;
DROP TABLE Contas CASCADE CONSTRAINTS;
DROP TABLE Clientes CASCADE CONSTRAINTS;
DROP TABLE Gerentes CASCADE CONSTRAINTS;
DROP TABLE Telefones CASCADE CONSTRAINTS;
DROP TABLE Enderecos CASCADE CONSTRAINTS;
DROP TABLE Usuarios CASCADE CONSTRAINTS;
DROP TABLE StatusParcelasEmprestimo CASCADE CONSTRAINTS;
DROP TABLE StatusEmprestimo CASCADE CONSTRAINTS;
DROP TABLE TiposMovimento CASCADE CONSTRAINTS;
DROP TABLE TiposInvestimento CASCADE CONSTRAINTS;
DROP TABLE StatusConta CASCADE CONSTRAINTS;
DROP TABLE TiposUsuario CASCADE CONSTRAINTS;
--============================================
-- 2. TABELAS SECUNDÁRIAS (LOOKUP / ENUM)
--============================================

CREATE TABLE TiposUsuario (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(20 CHAR) NOT NULL
);

CREATE TABLE StatusConta (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_status VARCHAR2(50 CHAR) NOT NULL
);

CREATE TABLE TiposInvestimento (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150 CHAR) NOT NULL,
    rentabilidade_mes NUMBER(10,6),
    carencia_dias NUMBER(10) NOT NULL,
    valorMinimo NUMBER(10,2) DEFAULT 0.00 NOT NULL
);

CREATE TABLE TiposMovimento (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_movimento VARCHAR2(50 CHAR) NOT NULL
);

CREATE TABLE StatusEmprestimo (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(20 CHAR) NOT NULL
);

CREATE TABLE StatusParcelasEmprestimo (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(50 CHAR) NOT NULL
);


--============================================
-- 3. TABELAS PRINCIPAIS (ENTIDADES)
--============================================

CREATE TABLE Usuarios (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CPF VARCHAR2(11 CHAR) NOT NULL UNIQUE,
    senha VARCHAR2(100 CHAR) NOT NULL, 
    email VARCHAR2(150 CHAR) NOT NULL UNIQUE,
    id_tipo_usuario NUMBER(10) NOT NULL
);

CREATE TABLE Enderecos (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logradouro VARCHAR2(255 CHAR) NOT NULL,
    numero NUMBER(10),
    complemento VARCHAR2(255 CHAR),
    bairro VARCHAR2(150 CHAR) NOT NULL,
    cidade VARCHAR2(150 CHAR) NOT NULL,
    estado VARCHAR2(2 CHAR) NOT NULL,
    cep VARCHAR2(9 CHAR) NOT NULL
);

CREATE TABLE Telefones (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_pais NUMBER(10) NOT NULL,
    cod_area NUMBER(10) NOT NULL,
    numero NUMBER(10) NOT NULL
);

CREATE TABLE Gerentes (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150 CHAR) NOT NULL,
    data_nascimento DATE NOT NULL,
    id_usuario NUMBER(10) NOT NULL
);

CREATE TABLE Clientes (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150 CHAR) NOT NULL,
    data_nascimento DATE NOT NULL,
    data_cadastro DATE NOT NULL,
    foto_url VARCHAR2(500 CHAR),
    id_usuario NUMBER(10) NOT NULL,
    id_endereco NUMBER(10) NOT NULL,
    id_telefone NUMBER(10) NOT NULL
);

CREATE TABLE Contas (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_conta VARCHAR2(10 CHAR) NOT NULL,
    saldo NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    data_abertura DATE NOT NULL,
    id_status_conta NUMBER(10) NOT NULL,
    id_cliente NUMBER(10) NOT NULL UNIQUE
);

CREATE TABLE AplicacoesInvestimentos (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_aplicado NUMBER(10,2) NOT NULL,
    data_aplicacao DATE NOT NULL,
    id_conta NUMBER(10) NOT NULL,
    id_tipo_investimento NUMBER(10) NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'ATIVA'
);

CREATE TABLE Movimentacoes (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor NUMBER(10,2) NOT NULL,
    data_movimento DATE NOT NULL,
    id_conta NUMBER(10) NOT NULL,
    id_conta_destino NUMBER(10),
    id_tipo_movimento NUMBER(10) NOT NULL
);

CREATE TABLE Emprestimos (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_total NUMBER(10,2) NOT NULL,
    valor_entrada NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    data_contratacao DATE NOT NULL,
    numeros_parcelas NUMBER(10) NOT NULL,
    taxa_juros FLOAT NOT NULL,
    id_conta NUMBER(10) NOT NULL,
    id_status_emprestimo NUMBER(10) NOT NULL
);

CREATE TABLE ParcelasEmprestimos (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_parcela NUMBER(10) NOT NULL,
    valor_parcela NUMBER(10,2) NOT NULL,
    data_vencimento DATE NOT NULL,
    valor_pago NUMBER(10,2),
    data_pagamento DATE,
    id_emprestimo NUMBER(10) NOT NULL,
    id_status_parcela NUMBER(10) NOT NULL,
    valor_amortizacao NUMBER(10,2),
    valor_juros NUMBER(10,2),
    saldo_devedor_apos_pagamento NUMBER(10,2)
); 

CREATE TABLE RecuperacaoSenha (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    token VARCHAR2(100 CHAR) NOT NULL,
    data_expiracao DATE NOT NULL,
    usado CHAR(1 CHAR) DEFAULT 'N'
);


--============================================
-- 4. MAPEAMENTO DE CHAVES ESTRANGEIRAS (FK)
--============================================

ALTER TABLE Usuarios ADD CONSTRAINT fk_Usuarios_TipoUsuario 
    FOREIGN KEY (id_tipo_usuario) REFERENCES TiposUsuario(id);

ALTER TABLE Clientes ADD CONSTRAINT fk_Clientes_Usuario 
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id);
    
ALTER TABLE Clientes ADD CONSTRAINT fk_Clientes_Telefone 
    FOREIGN KEY (id_telefone) REFERENCES Telefones(id);
    
ALTER TABLE Clientes ADD CONSTRAINT fk_Clientes_Endereco 
    FOREIGN KEY (id_endereco) REFERENCES Enderecos(id);
    
ALTER TABLE Gerentes ADD CONSTRAINT fk_Gerentes_Usuario 
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id);

ALTER TABLE Contas ADD CONSTRAINT fk_Contas_Status 
    FOREIGN KEY (id_status_conta) REFERENCES StatusConta(id);
    
ALTER TABLE Contas ADD CONSTRAINT fk_Conta_Clientes 
    FOREIGN KEY (id_cliente) REFERENCES Clientes(id);

ALTER TABLE AplicacoesInvestimentos ADD CONSTRAINT fk_Aplicacoes_Tipo 
    FOREIGN KEY (id_tipo_investimento) REFERENCES TiposInvestimento(id);
    
ALTER TABLE AplicacoesInvestimentos ADD CONSTRAINT fk_Aplicacoes_Conta 
    FOREIGN KEY (id_conta) REFERENCES Contas(id);

ALTER TABLE Movimentacoes ADD CONSTRAINT fk_Movimentacoes_Conta 
    FOREIGN KEY (id_conta) REFERENCES Contas(id);

ALTER TABLE Movimentacoes ADD CONSTRAINT fk_Movimentacoes_Conta_Destino 
    FOREIGN KEY (id_conta_destino) REFERENCES Contas(id);
    
ALTER TABLE Movimentacoes ADD CONSTRAINT fk_Movimentacoes_Tipo 
    FOREIGN KEY (id_tipo_movimento) REFERENCES TiposMovimento(id);

ALTER TABLE Emprestimos ADD CONSTRAINT fk_Emprestimos_Conta 
    FOREIGN KEY (id_conta) REFERENCES Contas(id);
    
ALTER TABLE Emprestimos ADD CONSTRAINT fk_Emprestimos_Status 
    FOREIGN KEY (id_status_emprestimo) REFERENCES StatusEmprestimo(id);

ALTER TABLE ParcelasEmprestimos ADD CONSTRAINT fk_Parcelas_Status 
    FOREIGN KEY (id_status_parcela) REFERENCES StatusParcelasEmprestimo(id);
    
ALTER TABLE ParcelasEmprestimos ADD CONSTRAINT fk_Parcelas_Emprestimo 
    FOREIGN KEY (id_emprestimo) REFERENCES Emprestimos(id);

--============================================
-- 5. CARGA INICIAL DE DADOS (TESTES SEMANA 1)
--============================================

-- Inserindo Enums de Tipo de Usuário
INSERT INTO TiposUsuario (tipo) VALUES ('CLIENTE');
INSERT INTO TiposUsuario (tipo) VALUES ('GERENTE');

-- Inserindo Enums de Status de Conta
INSERT INTO StatusConta (nome_status) VALUES ('PENDENTE');
INSERT INTO StatusConta (nome_status) VALUES ('ATIVA');
INSERT INTO StatusConta (nome_status) VALUES ('INATIVA');
INSERT INTO StatusConta (nome_status) VALUES ('REJEITADA');

-- Criando Usuário Cliente Inicial (Ganha ID 1 automaticamente)
INSERT INTO Usuarios (CPF, senha, email, id_tipo_usuario)
VALUES ('12345678901', 'senha123', 'cliente@ifbank.com', 1);

-- Criando Usuário Gerente Inicial (Ganha ID 2 automaticamente)
INSERT INTO Usuarios (CPF, senha, email, id_tipo_usuario)
VALUES ('55332581504', 'senha321', 'gerente@ifbank.com', 2);

-- Criando Gerente associado ao usuário 2 (Ganha ID 2 automaticamente)
INSERT INTO Gerentes(nome,data_nascimento,id_usuario)
VALUES ('Bianca Garcia', TO_DATE('1994-02-03', 'YYYY-MM-DD'),2);

-- Criando dados de Perfil associados (Ganha ID 1 em tudo automaticamente)
INSERT INTO Enderecos (logradouro, numero, bairro, cidade, estado, cep)
VALUES ('Rua Ficticia', 10, 'Centro', 'Araraquara', 'SP', '14800-000');

INSERT INTO Telefones (cod_pais, cod_area, numero)
VALUES (55, 16, 999999999);

INSERT INTO Clientes (nome, data_nascimento, data_cadastro,foto_url,id_usuario, id_endereco, id_telefone)
VALUES ('Usuário de Teste', TO_DATE('1990-01-01', 'YYYY-MM-DD'), SYSDATE,'caminho relativo',1, 1, 1);

-- Criando a Conta Vinculada Ativa (Ganha ID 1)
INSERT INTO Contas (numero_conta, saldo, data_abertura, id_status_conta, id_cliente)
VALUES ('10001-2', 500.00, SYSDATE, 1, 1);

COMMIT;


